language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  directories:
    - ./ui/node_modules
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./prepare.sh

before_install:
  - sudo service mysql stop

