language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - mysql

cache:
  directories:
    - ./ui/node_modules
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./prepare.sh

before_install:
  - mysql -e 'CREATE DATABASE retroquest;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('retroquest') where User='root';update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo service mysql restart
