language: java
jdk:
  - oraclejdk8

services:
  - mysql

addons:
  chrome: stable

cache:
  directories:
    - ./ui/node_modules
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./prepare.sh
