language: java
jdk:
  - oraclejdk8

sudo: required

services:
  - docker

cache:
  directories:
    - ./ui/node_modules
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  - SPRING_PROFILES_ACTIVE=docker

before_install:
  - sudo service mysql stop

install:
  - cd ./ui && npm install && cd ..
  - ./gradlew assemble

script:
  - cd ./ui && npm run lint && npm run sass-lint && npm run unit && cd ..
  - ./gradlew check dockerApiTest


